### ISSUE TITLE
Allow z-index to be customizable

### ISSUE THREAD

**Issue by Hiro-Nakamura** [arendjr/selectivity#10]
I'm currently using selectivity in a project, and it sits next to another widget that also allows a popup.  However the ``` z-index : 9999 ``` on the selectivity ``` <div> ```  causes the selectivity widget to appear over the other popup.

It would be helpful to provide an option to allow us to modify how it displays to fix these kinds of conflicts.

Something like this maybe:
```javascript
$('#tag-id').selectivity({
    items: [ {id:0, text:'no items loaded' }],
    multiple: true,
    placeholder:label,
    foregroundZIndex:999
});
```

**Comment by arendjr** [comment]
Sounds like a good idea! Will try to pick this up soon.

**Comment by n8n8baby** [comment]
Is there a particular reason you include it explicitly in the HTML? It seems like it should just use the CSS.

**Comment by arendjr** [comment]
No, I don't think so. I agree the preferable solution would be to handle this in CSS.

**Comment by arendjr** [comment]
The z-index can now be adjusted by just changing the CSS. I hope this suits your needs!

**Comment by Hiro-Nakamura** [comment]
Excellent!  Thanks!
