### ISSUE TITLE
Removing dropdown prevents mouseleave event to bubble to base-selectivity.

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#107]
Apparently removing the dropdown prevents the mouseleave to bubble higher.

So what we should do is not to remove the dropdown when selecting an item but just hide it and open it again when the dropdown is opened.
Also deleting the dropdown and recreating it every time is bad for performance. 

After a fast lookup this might be a pretty big refactoring but the performance gain would be substantial with big lists.

**Comment by niom** [comment]
This for example will leave hover class to the base element since the hover disabling event does not bubble. If the dropdown is hidden instead of removed the bubbling will happen and the hover is disabled.

**Comment by niom** [comment]
Problem is reproduced in: https://arendjr.github.io/selectivity/

scroll the Select a single city select box to the top of the screen. Select an item that's not on top of the select box.  hover class is still enabled.

Doing the same when you hack the dropdown to hide instead of remove the hover class is removed since the mouseleave bubles all the way.

**Comment by arendjr** [comment]
I've made a change to make the `close()` function remove the dropdown after a 1ms timeout. This should solve the issue.

Will be merged to master soon and be included in the 3.0 release.
