### ISSUE TITLE
Question about string escaping in templates

### ISSUE THREAD

**Issue by glafarge** [arendjr/selectivity#109]
For the moment, string escaping is used like the following : 

```js
    multipleSelectedItem: function(options) {
        var extraClass = (options.highlighted ? ' highlighted' : '');
        return (
            '<span class="selectivity-multiple-selected-item' + extraClass + '" ' +
                  'data-item-id="' + escape(options.id) + '">' +
                (options.removable ? '<a class="selectivity-multiple-selected-item-remove">' +
                                         '<i class="fa fa-remove"></i>' +
                                     '</a>'
                                   : '') +
                escape(options.text) +
            '</span>'
        );
    },
```

by the use of escape() function
```js
  escape(options.text)
```

We could use an other approach (note that escape() is deprecated) like the following.
This would also allow the use of space character for labeling.

```javascript
/**
 * Escape a string so it can be used safely in templates.
 * Allow the use of white space.
 *
 * @param string The string to escape.
 *
 * @return The encoded string.
 */
Selectivity.escape = function(string) {
    return encodeURIComponent(String(string)).replace(/%20/g, ' ');
};
```

=> The whitespace permission could also be set as an option.

What do you think about this ?
I can make a PR if you want.

**Comment by arendjr** [comment]
Hi there, did you notice the escape() function is not the default JavaScript escape(), but rather lodash's escape()? There should be no problems with whitespace with that...

**Comment by glafarge** [comment]
I had not paid attention, sorry !
My error came from a template option out of Selectivity scope :) So the native JS function was called instead of the lodash's one.
