### ISSUE TITLE
Select with empty value is no longer empty after init

### ISSUE THREAD

**Issue by Stenvdb** [arendjr/selectivity#110]
When I init the plugin on a select that has an option with an empty value, that value is being replaced with the option's text. Should be able to leave it empty (ie for validation).

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Stenvdb** [comment]
- What steps can be used to reproduce the issue?
  - Add a select with empty option
- What is the bug and what is the expected outcome?
  - Empty value of option is replaced with it's text value
- What browser(s) and Operating System have you tested with?
  - Latest browsers, osx
- Does the bug happen consistently across all tested browsers?
  - Yes
- Can you reproduce this issue on the examples page?
  - Doesn't apply
- What version of jQuery are you using? And what version of Select2?
 - Latest
- Are you using Select2 with other plugins?
  - Yes, but doesn't change the issue

https://jsfiddle.net/s6ocqsfb/
First item no longer has an empty value

**Comment by Stenvdb** [comment]
Another edit.. this could be fixed with the placeholder option but that doesn't seem to work. Also in the demos folder (jquery.html file) there is an example (the #single-select-box example) with an placeholder option set, but that seems to be ignored.

**Comment by arendjr** [comment]
Hi there, I agree it would be appropriate to use placeholder option for this, but I cannot reproduce the issues you seem to be having with placeholders. When you tried the demo, you used the jQuery version that's in the vendor directory, right? Or did you manually update that one to the latest?

I'll look into why the empty value is overwritten though.

**Comment by arendjr** [comment]
Oh, is it possible you tried to add the `placeholder` attribute to the `select` element instead of the `data-placeholder` attribute, perhaps?

I was surprised at first as well, but HTML5 doesn't define a `placeholder` attribute for the `select` element, which is why Selectivity uses `data-placeholder` instead :)
