### ISSUE TITLE
How to POST

### ISSUE THREAD

**Issue by Zabanya** [arendjr/selectivity#112]
How do I use POST instead of GET, I tried method: "POST" but it is not working.
is it changeable via "transport":function({})?

Regards

**Comment by arendjr** [comment]
Any parameters you define on the `ajax` option that are not explicitly used by Selectivity are passed directly to the *transport*, which by default is `$.ajax()`. I think `$.ajax()` uses the `type` option to specify the HTTP method, so `type: 'POST'` should do the trick.
