### ISSUE TITLE
Add a cache option for static db

### ISSUE THREAD

**Issue by glafarge** [arendjr/selectivity#119]
When we have to deal with static json file.
What do you think about serving cached file ?

- First request : getting fresh new json file
- Second time : if url is the same as previous call, serve cached file

This will improve the speed for specific use cases.

However the filtering part must be done client side. We should give an example.
Let me know your opinion...

**Comment by glafarge** [comment]
We could also give the user a choice to generate cache array before the user input to be more reactive. Does it need to be implemented in library directly ? That a good question...

**Comment by arendjr** [comment]
Hi there, I think it's an interesting use case. But I would suggest implementing a custom AJAX "transport" that would take care of this, rather than implementing it in the library directly.
Cheers!

**Comment by glafarge** [comment]
OK good for me ! Thx :)
