### ISSUE TITLE
allowClear - Single <select> instance

### ISSUE THREAD

**Issue by syosoft** [arendjr/selectivity#120]
Does the allowClear:true work on single option < select >? I've yet to figure out how to set it up and I see all of the examples are using an < input > field... Seems like this *should be* a feature you would've implemented already -- not sure what I'm doing wrong.

I am not setting up the < select > with an "empty value option" - didn't read that was a requirement, thou I did try it with one.

Thanks.

**Comment by syosoft** [comment]
Looks like it is based on lines 146-150, 241-246 in https://github.com/arendjr/selectivity/blob/master/src/selectivity-single.js 

The "x" isn't showing up for me thou and I'm unaware of the method to console.log(el.selectivity.options) so i can see if allowClear is set to true/false.

**Comment by syosoft** [comment]
Hrm... anyone?

**Comment by arendjr** [comment]
Yes, the option should work on single-select inputs. But are you loading font awesome? The default templates rely on it to display icons (including the "x" you mention).

**Comment by syosoft** [comment]
Ok, great. I'm currently using http://kudakurage.com/ligature_symbols/ throughout my app. I'll dig through the code a bit later and see where I need to mod it.

Thanks for the heads up.

**Comment by syosoft** [comment]
Good call, overwrote the template and voila!

**Comment by arendjr** [comment]
Glad I could help!
