### ISSUE TITLE
Is Zepto.js required?

### ISSUE THREAD

**Issue by SoftCircuits** [arendjr/selectivity#121]
When you say this plugin is for jQuery and Zepto.js, does that mean both libraries are required?

I like a lot of things about this component, but I'm just using jQuery and am looking for a solution that doesn't require additional libraries.

**Comment by syosoft** [comment]
... best to just try it. And no, both are not required...

**Comment by arendjr** [comment]
Hehe, syosoft is right. It will work as long as one or the other is loaded. Cheers!

**Comment by damnko** [comment]
Hi, I have been trying with no success to use Selectivity without jQuery AND Zepto.

In the homepage I read:
> Selectivity.js can be used without any external libraries, but also offers a jQuery build that is compatible with both jQuery (including custom builds without Sizzle) and Zepto.js, and a build that is compatible with React.    

But this does not seem to be the same thing as you said in your last reply so I am a bit confused. If it can be used without jQuery and Zepto could you please give me an example on how to convert this
```
$('#example-1').selectivity({
    allowClear: true,
    items: ['Amsterdam', 'Antwerp'/*, ...*/],
    placeholder: 'No city selected'
});
```
to a non-jQuery version?
Thanks a lot!

**Comment by arendjr** [comment]
With version 3, you no longer need either jQuery or Zepto. But the sample you pasted will only work the jQuery build which *does* require one or the other.

If you want to use the vanilla version without any dependencies, that sample would become like this:

    const selectivity = new Selectivity.Inputs.Single({
        allowClear: true,
        element: document.querySelector('#example-1'),
        items: ['Amsterdam', 'Antwerp'/*, ...*/],
        placeholder: 'No city selected'
    });

**Comment by damnko** [comment]
Great and thanks for the prompt reply!
Any hint on why it works when importing _selectivity.min.js_ while when importing the non minified _selectivity.js_ I get `Uncaught ReferenceError: Selectivity is not defined`?

**Comment by arendjr** [comment]
Hm, that's a good question and it might be a bug... I'll look into that!

**Comment by damnko** [comment]
Ok thanks, will keep an eye on the thread.
