### ISSUE TITLE
Example Internalisation French Francais

### ISSUE THREAD

**Issue by janke31** [arendjr/selectivity#127]
Example french translation,traduction en Français
Code to add before selectivity call: 
`$(document).ready(function() {
    $.fn.selectivity.Locale = {

    ajaxError: function(term) { return 'Echec de la des resultats pour <b>' + escape(term) + '</b>'; },
    loading: 'Chargement...',
    loadMore: 'Plus de chargement...',
    needMoreCharacters: function(numCharacters) {
        return 'Entrer ' + numCharacters + ' caractère(s) de plus pour lancer la recherche';
    },
    noResults: 'Pas de résultats Pour',
    noResultsForTerm: function(term) { return 'Pas de résultats Pour <b>' + escape(term) + '</b>'; }

};
        ....`

**Comment by arendjr** [comment]
Thanks, but not exactly sure what to do with this.
