### ISSUE TITLE
Provide an NPM package

### ISSUE THREAD

**Issue by andrejcremoznik** [arendjr/selectivity#128]
Component is deprecated and I don't see why anyone would use Bower when NPM can be used for everything. Please provide selectivity as an NPM package.

**Comment by arendjr** [comment]
I agree, I will do this for the next (major) release. Don't know yet when it'll be though...

**Comment by remexre** [comment]
It would be greatly appreciated if this would be implemented as soon as possible, even if it possibly involved e.g. a hotfix branch -- our build process uses `rollup`, which can only import NPM modules. Thanks!

**Comment by arendjr** [comment]
I'm currently working on what I've dubbed my "API independent rewrite". It's quite a disruptive branch that'll make Selectivity's jQuery dependency fully optional and I'll also offer an optional React API as alternative to the jQuery one. This branch also reorganises the modules and plugins somewhat, which will make it feasible to selectively `require()` the modules you're interested in so that you can get the advantages of a custom build when using Browserify/Webpack without having to make an actual custom build (compare it to how lodash v4 allows to `require('lodash/padStart')` for example).

So, good stuff is coming for the NPM build, but it'll take a bit more work before everything is stable again, so please bear with me :)

**Comment by arendjr** [comment]
Okay, so I've just published Selectivity 3.0.0-alpha1 on NPM. You should expect it to be rough around the edges, given that version 3 is a major refactoring and it's the first NPM build, but here's the current status...

You can install the release using `npm install selectivity@3.0.0-alpha1`. Once installed, you should realize Selectivity is very modular and is usually assembled through a build script. For the NPM release, I don't want to lose the flexibility of the build script that allows you to cherry-pick which modules you're using, and only include those in your final bundle. So for now, you will need to require every module you're using... For example:

    require('selectivity/dropdown'); // you'll surely want this
    require('selectivity/apis/jquery'); // this attaches Selectivity to $.fn.selectivity
    require('selectivity/input-types/single'); // for single-value inputs
    require('selectivity/input-types/multiple'); // for multi-value inputs
    require('selectivity/plugins/keyboard'); // to be able to use arrow keys to navigate dropdowns
    require('selectivity/submenu'); // if you want to have submenus
    // etc... see the README for all modules

Finally, `var Selectivity = require('selectivity');` will expose the main Selectivity object which is useful if you want to attach your own plugins, for example. Also, if you're adventurous, you could use it to attach instances to DOM nodes directly without relying on the jQuery API at all.

For a later release I want to allow people to simply do `require('selectivity/jquery')` as a shortcut for a jQuery build that includes all applicable plugins. I hope that would provide a good balance between convenience and flexibility then.

I'll also be adding a React API before 3.0 goes into beta.

If you want to try it out, please be my guest! Please also check the CHANGELOG for an idea of what might need to migrated. Bug reports and other feedback will be appreciated.

Cheers!

PS.: The documentation on the project site is still for version 2.1... I'll try to update ASAP.

**Comment by arendjr** [comment]
Okay, I've just published 3.0.0-beta1. It provides the convenience entry-points so you can do `require('selectivity/jquery')` to start using the jQuery API with all the plugins.

I've updated the README, so it contains (hopefully) clear instructions on how to use Selectivity from NPM.

So I consider this ticket closed now :)
