### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by tuelsch** [arendjr/selectivity#13]
There seem to be trailing commas in some modules (I found 3 while compiling my custom version of selectivity). I will create a pull request which removes the trailing commas I found. The google closure compiler http://closure-compiler.appspot.com/home reported these errors while trying to minify the custom script.

**Comment by arendjr** [comment]
Cool. Looking forward to the PR :)

**Comment by arendjr** [comment]
Merged #15.

**Comment by arendjr** [comment]
I've set up JSHint to be more strict in 835d0a0f1fe, to make sure trailing commas won't sneak in again :)
