### ISSUE TITLE
Hide selected value from dropdown

### ISSUE THREAD

**Issue by 1337LutZ** [arendjr/selectivity#135]
Heya,

Im not sure if this is possible / has been asked before:

Is it possible to hide the current value from the options in the dropdown when it opens?

Regards,
Adrian

**Comment by 1337LutZ** [comment]
I created a temporary "hacky" fix for myself.

`templates: {
          resultItem: function(item) {
            
            var id = $(event.target).parents('.dropdown').find('.selectivity-single-selected-item').data('item-id');
            if(id !== item.id)
              return ('<div class="selectivity-result-item" data-item-id="' + item.id + '">'+ item.text +'</div>');
            
          }
        }`

**Comment by arendjr** [comment]
This is done for multi-value selects by default. The `filterResults()` method is used for this purpose. Single-value inputs don't do this, but if you'd want it, overriding that method would be the less hacky way to do it :)

**Comment by 1337LutZ** [comment]
Can you give me a suggestion on how doing this? Javascript isnt my A+++ skill. :(
