### ISSUE TITLE
selectivity-single-selected-item-remove disappears but the selected value is still present when I submit the form

### ISSUE THREAD

**Issue by streethawk** [arendjr/selectivity#136]
I am using the selectivity input like:
`<form:select path="formVariable" class="selectivity-input" name="traditional[single]">
       <form:option value="">--Select--</form:option>
        <form:options items="${formVariable}"/>
</form:select>`

And the script is declared as:

`$('#formVariable').selectivity({
        allowClear: true,
        placeholder: "Select an Item from the List"
    });`

When I click on the cross button after making a selection from the drop-down, I can see that the <li> disappears but the value is still present when I submit the form.

**Comment by arendjr** [comment]
Thanks for the report. I think I got a fix in the works, but it'll take a little while before I can merge it back to master, so I'll come back to it.

**Comment by arendjr** [comment]
The fix should now be in master, and will be release with 3.0.

**Comment by kamal-2034** [comment]
Hello Arend,

Can you please post the fix that you made to clear the old value which were removed after clicking the cross icon. I need to fix that in my one of project.

Can you please post the fix here. 

Thanks

**Comment by arendjr** [comment]
I cannot guarantee this will work exactly as it should, because more changed than just this fix, but in selectivity-traditional.js, you can try replacing the bindTraditionalSelectEvents method with this:

    function bindTraditionalSelectEvents(selectivity) {
        var $el = $(selectivity.el);
        $el.on('change', function(event) {
            var value = event.originalEvent.value;
            $el.prev('select').val($.type(value) === 'array' ? value.slice(0) : value).trigger(event);
        });
    }

**Comment by kamal-2034** [comment]
Thanks Arend
