### ISSUE TITLE
Has conflicts with Bootstrap styles

### ISSUE THREAD

**Issue by Huashfx** [arendjr/selectivity#14]
If import Bootstrap with Selectivity will got bad view...can't see remove button and placeholder text looks terrible

**Comment by arendjr** [comment]
Should hopefully be fixed with c5d3e05 now. Can you confirm please?

**Comment by wong2** [comment]
I'm facing the same problem right now, even with the latest build, the style is still bad:

![](http://doora.qiniudn.com/utl83.png)

code:

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="collapse navbar-collapse">
            <form class="navbar-form navbar-right">
              <div id="topic-search" class="selectivity-input"></div>
            </form>
          </div>
        </nav>
    </body>

**Comment by wong2** [comment]
the problem seems to be with:

https://github.com/arendjr/selectivity/blob/master/styles/selectivity-single.less#L22

and 

https://github.com/arendjr/selectivity/blob/master/styles/selectivity-single.less#L39

if I disabled these lines, the style is normal

**Comment by arendjr** [comment]
Hm, that's unfortunate because these lines are necessary if Bootstrap is not loaded. I'm not having a Bootstrap setup right now to test with. Can you see what Bootstrap is doing that makes these styles act different?

**Comment by msx2** [comment]
@arendjr Bootstrap sets `box-sizing: border-box` for all elements (using `*`). That's what breaks here :)

**Comment by arendjr** [comment]
Okay, merged. Thanks a lot for the PR and the explanation!
