### ISSUE TITLE
ReadOnly clears data

### ISSUE THREAD

**Issue by marcbecker** [arendjr/selectivity#144]
When changing a field to "readOnly" by means of this command 

`$(".infoSection` .selectivity-input").selectivity('setOptions', { readOnly: true })

 the entire field is being cleared and I cannot enter new values through clicking after i set it back to false. The dropdown appears but the values are not entered. Through jquery it does not work either. I tried the following. 

`$(".infoSection` .selectivity-input").selectivity("data",taskDOM.find(".selectivity-input").eq(0).selectivity("data")); 

Do you have any idea how to fix that? Because not everybody should be able to change the input.

**Comment by arendjr** [comment]
Looks like you hit a real bug when it came to dynamically changing the `readOnly` option. The fix is in master now.

Cheers!
