### ISSUE TITLE
Initial selection and fetch remote results

### ISSUE THREAD

**Issue by reidransom** [arendjr/selectivity#150]
Is there a way to set the initial selection while also using ajax to fetch new results?

**Comment by arendjr** [comment]
Hi, sorry for the late reply. But yes, that should be possible. You can use the ajax module for fetching results, but you can still set the initial value using the `value` or `data` options during initialization. There's also an `initSelection` option that can (asynchronously) get the corresponding text for your initial value.

Does that answer your question?

**Comment by reidransom** [comment]
Yup that works.  Thank you!
