### ISSUE TITLE
With closeOnSelect selecting outside dropdown causes JavaScript error.

### ISSUE THREAD

**Issue by AndorLundgren** [arendjr/selectivity#156]
If you have option closeOnSelect = false and use mouse to click anywhere outside the select list there is an error in event off because eventname "selectivity-selecting" does not exist in events.
Have code below:

<div class="select-multiple"></div>

<script>
 $('.select-multiple')
        .selectivity({
            items: ['Amsterdam', 'Antwerp'],
            multiple: true,
            placeholder: 'Type to search a city',
            closeOnSelect: false
        });
</script>

**Comment by arendjr** [comment]
Thanks for the report, but I think your code snippet got lost in translation :)

**Comment by AndorLundgren** [comment]
Thank  you for fast response. Yes my code snippet ran away. :)
````javascript
<div class="select-multiple"></div>
<script>
 $('.select-multiple')
        .selectivity({
            items: ['Amsterdam', 'Antwerp'],
            multiple: true,
            placeholder: 'Type to search a city',
            closeOnSelect: false
        });
</script>

**Comment by arendjr** [comment]
Thanks, I'll look into it!

**Comment by AndorLundgren** [comment]
What causes the error is that the event selectivity-selecting is removed when it does not exist.

You add the event selectivity-selecting conditionally:
In dropdown.js:
```
if (selectivity.options.closeOnSelect !== false) {
        selectivity.events.on('selectivity-selecting', this.close);
}
```
You remove the event on close:
In dropdown.js:
```
this.selectivity.events.off('selectivity-selecting', this.close);
```
This causes the turning off the event in event-listener.js to break;
```
// here the this.events[eventName] to be undefined and undefined[selector] creates the js error
var events = this.events[eventName][selector];
```

Not sure what solution is the best but adding the conditional statement to the close statement would probably work:
In dropdown.js:
```
close: function() {
    if (!this._closed) {
        this._closed = true;
        removeElement(this.el);
            
        if (this.selectivity.options.closeOnSelect !== false) {
            this.selectivity.events.off('selectivity-selecting', this.close);
        }

        this.triggerClose();
        this._removeScrollListeners();
    }
},
```

**Comment by arendjr** [comment]
Thanks for the detailed description! I think the preferred option would be for the event-listener not to break if it has to remove a non-existing event. I'll create a test for that and create a fix. Thanks!

**Comment by AndorLundgren** [comment]
Thank you.
