### ISSUE TITLE
Have problem understanding how to set Local in jQuery.

### ISSUE THREAD

**Issue by AndorLundgren** [arendjr/selectivity#158]
Hi, great selection library.

Need to set language (or Locale variable) on selectivity with use of selectivity-jquery.js and have tried:
```
<div class="my-select"></div> 
<script>
       $(document).ready(function () {
            $.fn.selectivity.Locale = {
                noResultsForTerm: function (term) {
                    return 'Can not see this text <b>' + escape(term) + '</b>';
                }
            };
            $('.my-select').selectivity({
                items: ['Amsterdam', 'Antwerp'],
                placeholder: 'Type to search a city'
            });
     });
</script>
```
And it did not work.
Have seen and read [Configuring the local messages #69](https://github.com/arendjr/selectivity/issues/69) which points to [msx2/selectivity-rails example of setting language](https://github.com/msx2/selectivity-rails/blob/master/app/assets/javascripts/selectivity.pl_PL.js.coffee) which I think tells me to the above way.
Is there a new way to set the language in 3.0?

**Comment by AndorLundgren** [comment]
Do not understand how to do this the best way.
The Locale object is exported as a commonjs module and included in all places used in the code.
In the selectivity-jquery.js file I see the commonjs code and to my understanding the jQuery code is created with use of browserify and dereq.
This means that even if I try to do some own locale.js override file, the code that loads the translations will always be the a local local.js found in src folder of the project.
My solution to the problem is replacing the local.js file and build my own selectivity-jquery.js file.
I do not think this is the best way for users to have to do, so if anyone know an other way when using the selectivity-jquery.js file I would like know how to do it.

**Comment by arendjr** [comment]
This indeed seems an oversight in the 3.0 release. If you install Selectivity through NPM this shouldn't be a big problem, as you can just assign your own messages like this:

    var Selectivity = require('selectivity');
    Selectivity.Locale.noResultsForTerm = function (term) {
        return 'Can not see this text <b>' + escape(term) + '</b>';
    };

But if you want to use a pre-built version it appears there's no easy way to get to the Selectivity object for customization. I hadn't noticed this yet because I indeed use custom builds myself as well. I'll think about how I can make this more accessible for the next release...

**Comment by arendjr** [comment]
I've also added an explanation on how to do customizations to the README: 5e9d99c
