### ISSUE TITLE
Having problem to change the prop multiple dynamically. Using react.

### ISSUE THREAD

**Issue by Chesla** [arendjr/selectivity#159]
<Selective
										    onChange={(event)=>{
										    	this.setState({
										    		dependent_sub_id:event.value
										    	})
										    }}
										    multiple={this.state.dependent_id ==='category'?true:false}
										    value={this.state.dependent_sub_id}
										    items={this.state.dependentFieldsObj[this.state.dependent_id] || []}
										    showSearchInputInDropdown={false}
										    placeholder='Dependent Sub List'
										/>

In this case, the multiple is getting set to false initially , but after the condition is set to true for multiple, the also it is not changing to multiple type.

**Comment by arendjr** [comment]
I'm sorry, this was never meant to be changed dynamically. Technically it would be a huge job to fix this, but also functionally there's too many edge-cases to consider (starting with: what should happen if you've selected multiple items and then change `multiple` to `false`?).

I will make this more clear in the documentation so as not to give false hope...

**Comment by Chesla** [comment]
Thanks for the clarity.
