### ISSUE TITLE
No longer getting distributable files when installing with NPM

### ISSUE THREAD

**Issue by mmikkel** [arendjr/selectivity#164]
I'm a bit confused.

Just did a fresh install of Selectivity via NPM, and I'm no longer getting any distributable files in `node_modules/selectivity` – which means that `require('selectivity')` or `require('selectivity/jquery')` doesn't work anymore.

After installing Selectivity's dependencies manually and running `npm run build` inside `node_modules/selectivity`, the distributable files are, er, built to `node_modules/selectivity/build` and I can do `require('selectivity/build/selectivity')` – but is it supposed to work like this? I could swear that I didn't have to do this manually on a project a few months ago; the distributables were available in the root Selectivity folder after installing.

Any pointers or info much appreciated. Thanks!

**Comment by arendjr** [comment]
Ai, yikes... That means my build process must be broken... will check it out!

**Comment by mmikkel** [comment]
Hey @arendjr – thanks for the fast reply! Good to know I'm not going crazy :)

**Comment by arendjr** [comment]
Okay, I've just published 3.0.2, that should fix it, I think. Still a bit surprised what went wrong 3.0.1 though, because I used the same script for creating the release...

**Comment by mmikkel** [comment]
Awesome @arendjr – confirmed fixed. Thanks a lot!

**Comment by alexcroox** [comment]
Looks like the 3.0.2 download is broken from the main website (latest release didn't contain any binary files)

**Comment by arendjr** [comment]
Yikes, seems I was too rushed when I fixed the NPM release... I've added a new tarball to the 3.0.2 release. Thanks for the notice!
