### ISSUE TITLE
allowClear: true, removable: false

### ISSUE THREAD

**Issue by alexcroox** [arendjr/selectivity#166]
For single selection elements I'd like to be able to allowClear (so the input can start without anything selected), but also avoid the clear icon appearing. It seems there is an option called `removable` which controls the visibility of this remove icon, but it isn't exposed to the api.

**Comment by arendjr** [comment]
This should already be possible by using a custom template. The removable option is indeed the template option that's used for this, so you can simply set a template that ignores the option.
