### ISSUE TITLE
"query" not called on search ?

### ISSUE THREAD

**Issue by mistic100** [arendjr/selectivity#169]
Hello,

I try to implement a search through submenus, for that I though I could use the "query" option to filter the options tree on user input.

See https://jsfiddle.net/Lmfpj9n8/

My problem is that the query method is called once on init with an empty term and then is never called again as the user enter text, the search is instead perfomed internally on the items already visible.

Am I missing something obvious ?

**Comment by arendjr** [comment]
I know such a use-case is possible, because I actually have implemented a selector like you're trying to achieve in our product as well. Could you try this again with the latest Selectivity version? I do know older versions had some issues coordinating queries between submenus.

**Comment by mistic100** [comment]
Oups didn't see cdnjs was not up to date (like, at all).

Is the last version available somewhere useable with jsfiddle ?

**Comment by arendjr** [comment]
You shouldn't use this as CDN, I think, but you can use the version that's used by the project website itself: https://arendjr.github.io/selectivity/javascripts/selectivity-jquery.js

**Comment by mistic100** [comment]
Ok I linked them from the demo page and it works https://jsfiddle.net/Lmfpj9n8/1/

If I may, as my self maintaining a lib and always complaining people are not submiting demo, you should ensure cdnjs is up to date.

**Comment by arendjr** [comment]
Yeah, that's good advise. I'll have a look into that! Thanks!
