### ISSUE TITLE
SingleSelectivity new Item

### ISSUE THREAD

**Issue by Antonimo** [arendjr/selectivity#17]
How can I enable creating new Item, like the email/multiple, but single, and with dropdown select?
( if category not found in the list, enter name of new category... )
use the query somehow?

**Comment by Antonimo** [comment]
I think I've got it https://github.com/Antonimo/selectivity/blob/master/src/selectivity-free-single.js  
I used a sticky "other" option that if selected a new input field will appear for entering new custom value;

**Comment by arendjr** [comment]
Sorry for the late reply!

I think it would've been possible to return the "other" option with the query function as well. The downside though would be that if you want to use a static items list, you need to reimplement searching through that list yourself in the query function. Anyway, good to see you've found a solution! :)

**Comment by Antonimo** [comment]
Ye, I really enjoyed extending the core, very modular design, very intuitive imho.  
but how is this maintainable, idk! yet ;)
