### ISSUE TITLE
unexpected removal happens in multiselect

### ISSUE THREAD

**Issue by StevenTew** [arendjr/selectivity#171]
**Example 1:**
1. Go to 'Select Multiple Cities' example: http://arendjr.github.io/selectivity/

2. type 'a' (see Amsterdam is highlighted)
![image](https://cloud.githubusercontent.com/assets/1876163/21991391/51492a44-dc0a-11e6-83ae-035bf9c41857.png)

3. hit return (see Amsterdam is added)
![image](https://cloud.githubusercontent.com/assets/1876163/21991326/0b4e72e2-dc0a-11e6-9dfa-4fdc05169889.png)

4. type 'a' again (see nothing is highlighted - but expected result is Antwerp is highlighted)
![image](https://cloud.githubusercontent.com/assets/1876163/21991372/3ffb63f6-dc0a-11e6-8bd2-da5c3e99abd1.png)

5. hit return (see Amsterdam is removed in error - expected results is Antwerp is added)
![image](https://cloud.githubusercontent.com/assets/1876163/21991411/633596ca-dc0a-11e6-8d01-91588323e20a.png)

Witnessed in the latest version of Chrome.

This becomes more of a problem when using grouped data with a multiselect: e.g. type 'spain', see Barcelona is highlighted, hit return to add Barcelona, then type 'spain' again (this time nothing is highlighted, but should be Madrid), hit return and Barcelona is removed (but expecting Madrid to be added to Barcelona).

**Comment by arendjr** [comment]
Thanks for the detailed description! Hope to get some time to tackle this soon.

**Comment by arendjr** [comment]
It appears this one already got fixed as part of #181 a while ago.
