### ISSUE TITLE
blur

### ISSUE THREAD

**Issue by Antonimo** [arendjr/selectivity#18]
on demo page https://arendjr.github.io/selectivity/
click on Select a city by timezone selectivity, then on Select a city by country. Both are open

**Comment by arendjr** [comment]
Aii... I must've broken that recently (and no tests are complaining about it). Good catch, I'll try to look into it soon. Thanks!

**Comment by arendjr** [comment]
It looks like I've put an incorrect version on the demo page (possibly without the 'backdrop' module). I've put the latest on there and it seems to work again.
