### ISSUE TITLE
Existing selection highlighted by default on multi-value search results

### ISSUE THREAD

**Issue by ahamid** [arendjr/selectivity#180]
When search results are rendered, the existing selections are filtered _out_.  However the entire set is used when assigning/picking the first highlighted item.  The result is that this item is not highlighted (because it is of course not even in the DOM), but it IS selected on `<Enter>` key - and the effect is that the existing selection is then toggled and _un_selected.  PR forthcoming.

**Comment by arendjr** [comment]
Thanks for the report and PR!
