### ISSUE TITLE
Add browser validation support

### ISSUE THREAD

**Issue by r4z3c** [arendjr/selectivity#187]
Hi,
I made a '2 minutes improvement' to the single input, which allows html5 browser validation to work properly. This could be an interesting enhancement? I want to contribute with these simple changes.

**Comment by arendjr** [comment]
Hi, this sounds like a good idea! I'd be happy to accept a PR for that. Do you think the changes are also testable? If so, I'd rather have an automated test to make sure the feature works as advertised as well.

When submitting a PR, please follow the coding style and make sure you don't break existing tests. Thanks!

**Comment by r4z3c** [comment]
So, I made improvements at two existing tests (one of jQuery, one of React), and created another two tests (one of jQuery, one of React). I think that is enough to handle and guarantee the changes. I also checked lint, and everything seems ok. Can you take a look on PR and give me a feedback?

https://github.com/arendjr/selectivity/pull/188

:)

**Comment by arendjr** [comment]
PR merged. Thanks!
