### ISSUE TITLE
selectivity-multiple - Enter - preventDefault

### ISSUE THREAD

**Issue by Antonimo** [arendjr/selectivity#19]
The multiple select while inside a form - Enter Key submits. I've fixed it this way:  
```
_keyHeld: function(event) {

        this._originalValue = this.$searchInput.val();
        
        if (event.keyCode === KEY_ENTER && !event.ctrlKey) {
            
            // console.log( this.dropdown );
            event.preventDefault();
        }
        
    }
```

**Comment by harfyt** [comment]
I faced the same issue on IE.
Thanks for the tip Antonimo.

**Comment by msx2** [comment]
@Antonimo I've added form to jQuery's demo page, used your solution from here and created #21

FYI @arendjr

**Comment by arendjr** [comment]
Thanks guys, the PR has been merged!
