### ISSUE TITLE
If i cant find anything for match,may i set the query param for default value?

### ISSUE THREAD

**Issue by goukixiao** [arendjr/selectivity#197]
Thanks for the great library.

When i type anything for search , it doesnt have anydata for match ,so i want set the query param for default value.

e.g.
datas = [1,2,3,4,5,6]

I type 7 , so i can not find anydata for match.
so ,i want set 7 for the "input value"

SORRY,MY ENGLISH IS TOO BAD.

**Comment by arendjr** [comment]
I'm sorry, this is not supported in the current version. It sounds like what you want would be accomplished through a "tagging" feature which also relates to #39. This will likely come in a future update, but I don't have an ETA for this atm.
