### ISSUE TITLE
Select multiple not close on Firefox

### ISSUE THREAD

**Issue by jmmccota** [arendjr/selectivity#198]
I'm using Selectivity Multiple with react.
The problem occur on firefox, various versions (I've tested since 40).
Using your own site https://arendjr.github.io/selectivity/ when you click on **Select multiple cities** and then click out of input field, the dropdown don't close.

**Comment by arendjr** [comment]
Thanks for the report. This was fixed by #194 but is not yet in any release.

**Comment by jmmccota** [comment]
Thank's. I'm waiting for new version!
