### ISSUE TITLE
How to set a default value?

### ISSUE THREAD

**Issue by pcarvajalh** [arendjr/selectivity#205]
Sorry to bother, I know this must be a basic, but can't find the way to make it work.

Basically, I want to do this:
< select name="player" >
< option value="1" >player 1</ option >
< option value="2" **selected** >player 2</ option >
< option value="3" >player 3</ option >
</ select >

I have the following code:
     var player = [
        { id: 1, text: 'player  1' }
       ,{ id: 2, text: 'player  2' }       
       ,{ id: 3, text: 'player 3' } 
        ];

    $('#player').selectivity({
        allowClear: true,
        items: player,
        data: [ { id: 2, text: 'player 2' }    ],
        placeholder: 'Select player...'
    });

Thanks in advance!

**Comment by arendjr** [comment]
Does it work if you use a single object instead of an array for the `data` field? The array should only be used for Selectivity instances with multiple selections.

**Comment by pcarvajalh** [comment]
No, I tried this way, but it does not work

    var player = [ 'player 1' ,'player 2','player 3'];

    $('#player').selectivity({
        allowClear: true,
        items: player,
        data: ['player 2'],
        placeholder: 'Select player...'
    });

**Comment by arendjr** [comment]
That second one should work if you replace `data` with `value`. Note that value always only contains IDs whereas data is always supposed to contain objects with `id` and `text` properties. 

If you use strings in the items array that's simply a short-hand for objects where the ID and text are the same.

**Comment by pcarvajalh** [comment]
got it! 

    var player = [        
     { id: 1, text: 'player 1' }       
    ,{ id: 2, text: 'player 2' }
    ,{ id: 3, text: 'player 3' }    
    ];

    $('#player').selectivity({        
    ,allowClear: true        
    ,items: player 
    ,value: 2        
    ,placeholder: 'Select player'
    });

(btw, I am working with the latest version of JQuery
https://code.jquery.com/jquery-3.2.1.min.js)

thank you very much!!

**Comment by arendjr** [comment]
Welcome!
