### ISSUE TITLE
Not empty on init

### ISSUE THREAD

**Issue by djvolk** [arendjr/selectivity#206]
Hi, I have a strange problem.

A simple example script: https://jsfiddle.net/17rn50fz/2/

```
<link href="https://arendjr.github.io/selectivity/stylesheets/selectivity-jquery.css" rel="stylesheet">
<script src="https://arendjr.github.io/selectivity/javascripts/jquery.js"></script>
<script src="https://arendjr.github.io/selectivity/javascripts/selectivity-jquery.js"></script>

<select id="test">
    <option value="1">Test 1</option>
    <option value="2">Test 2</option>
    <option value="3">Test 3</option>
    <option value="4">Test 4</option>
</select>

<script type="text/javascript">
$('#test').selectivity({
    allowClear: true,
    placeholder: 'empty',
});
</script>
```

And is always selected first options by default. I want it to be empty. If I add an empty option <option value></option>, it will be selected and display clear icon, not placeholder. 
Only selectivity('clear') method can set empty select.

**Comment by arendjr** [comment]
The preselection of the first option is standard HTML behavior, so the option is already selected even before Selectivity is initialized. Once Selectivity is initialized it just takes over the value that was selected in the HTML select. I think imediately calling "clear" is a fine way around that.

Alternatively you could initialize a plain div element and set the options using Selectivity's items array, to avoid this altogether.

Hope that answered your question.

**Comment by arendjr** [comment]
Oh, you might also try explicitly setting the value option to `null`. Does that override the value selected by the HTML select?
