### ISSUE TITLE
Dropdown positioning in relative container

### ISSUE THREAD

**Issue by msx2** [arendjr/selectivity#22]
After the recent changes there's an issue with positioning the dropdown inside relative container, e.g. add the following to one of the `<p>`aragraphs on demo pages that contain selectivity inputs:

```css
width: 50%;
margin: 0 auto;
position: relative;
```

This will result in:
![screen shot 2015-04-07 at 22 20 55](https://cloud.githubusercontent.com/assets/1129643/7032698/b1ee34ac-dd74-11e4-987c-5512e718ab54.png)

I wanted to update `gh-pages` branch to consist the newest build, and saw it happen there.

By the way, @arendjr, is there any way to contact you directly? I tried Twitter, but figured you don't use it on a daily basis :)

**Comment by sethlivingston** [comment]
+1

**Comment by msx2** [comment]
@sethlivingston @arendjr Here's what went a bit wrong and the moment this bug occured:

* dist - https://github.com/arendjr/selectivity/commit/a6ea06bee24a27d208df12e5b162b74158bb2e3e#diff-7d5ff9ae5ebd391a438716c392f40259L2352
* src - https://github.com/arendjr/selectivity/commit/a6ea06bee24a27d208df12e5b162b74158bb2e3e#diff-42740493c39ef39ba0e7d7b50fee7818L105

Right now the dropdown is injected after the element that triggers it. Previously it was appended to the `body`, that's why everything was working just fine.

The easiest solution would be to go back
