### ISSUE TITLE
Fetch failing

### ISSUE THREAD

**Issue by FiddlinBill** [arendjr/selectivity#223]
Downloaded and unzipped the latest selectivity. Everything works except for the ajax enabled case. I am getting this error even when I use the ajax example from the api that queries git repositories. Any ideas?

selectivity-jquery.js:2633 Uncaught TypeError: i(...).then(...).then(...).catch is not a function

Browsers tested: Chrome, Firefox

Seems like this has already been reported in #214

**Comment by arendjr** [comment]
Thanks for the report, I'll continue the discussion in #214.
