### ISSUE TITLE
Init cityselect with the value which call by queryFunction

### ISSUE THREAD

**Issue by cindyming** [arendjr/selectivity#228]
Hi,

I use the query to load the sub menu for city province, But we I use the val to init the selection, the label is showed correctly, How can I use the query to load the submenu items maually before set the init value?

I try to use the mouseover event, but it don't work.

Thanks
Cindy

**Comment by cindyming** [comment]
@arendjr can you please help me to check it?

**Comment by arendjr** [comment]
Hi Cindy,

Do I understand correctly you want the results of your submenu cached in advance so the submenu opens instantly?
You could consider using a memoized function inside your query function (if you’re unfamiliar with memoization, you could check out https://lodash.com/docs#memoize). Then you can call the memoized function at any point to prefill a cache of submenu items.

Hope that helped!
Arend jr.

**Comment by cindyming** [comment]
@arendjr , Sorry, Maybe I did't discribe the question clearly, I don't want to cache the submenu, I want to load the submenu before the mouse over action. I try to use the mouseover event to trigger the query function, but it don't work

**Comment by cindyming** [comment]
@arendjr can you please help on this? sorry for boring you
