### ISSUE TITLE
Adopt proper versioning

### ISSUE THREAD

**Issue by sethlivingston** [arendjr/selectivity#23]
Use GitHub releases, bump versions, and specify the versions for Bower.

**Comment by arendjr** [comment]
Isn't that what I'm doing? There's only a version 1.0 so far, which is a GitHub release and is the only version in Bower. The announcement for it is here: http://www.arendjr.nl/2015/03/select3-v10-released.html

There's not been enough changes (nor enough testing) to warrant a version bump. You're free to take the latest and greatest from GitHub of course, but I cannot guarantee there won't be bugs.

**Comment by sethlivingston** [comment]
I should have been more specific, sorry. Running `bower install --save selectivity` puts the following entry in `bower.json`:

        "selectivity": "*"

This means we get the latest version on every `bower update/install`, but we want to stick with the stable releases.

The reason it does that is that you don't have a semver-compliant tag in this repository. See the [http://bower.io/docs/creating-packages/#register](Register section) of the Bower.io documentation.

**Comment by arendjr** [comment]
Okay, I'll keep that in mind for the next version I'll publish then. I'll leave this issue open until then.

**Comment by sethlivingston** [comment]
I believe you can fix it simply by renaming your "v1.0" tag to "v1.0.0":

http://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag

See the first answer there.

**Comment by arendjr** [comment]
Okay, I've renamed the tag. Can you verify it works now?

**Comment by sethlivingston** [comment]
It works! Thanks, @arendjr!

**Comment by arendjr** [comment]
Great!

**Comment by sethlivingston** [comment]
No need to reopen this, but your "select3 => selectivity" commit came *after* the 1.0.0 tag. Looks like your best bet is to push a new release as soon as possible.

**Comment by arendjr** [comment]
New version has been published!
