### ISSUE TITLE
allow selecting parent as option

### ISSUE THREAD

**Issue by watsab** [arendjr/selectivity#231]
Hi!

I have a case where I need to select the parent of a group of options. Either it's not currently possible or I could not find an option allowing it. Could you please confirm that it's not possible (yet)?
If it is not, do you think it could be an option to add?

Thanks!

**Comment by arendjr** [comment]
I don’t understand the exact use case, but I don’t think that’s possible, no.

**Comment by watsab** [comment]
The use case is that I have different options that are hierarchically organised: somthing that would look like (althought the following data structure would not fit the expected model to properly work) :
```
{
  vegetable: [
    'carrot'
    'leek',
    'cabbage',
  ],
  fruit: [
    'strawberrry',
    'peach',
    'orange',
  ]
}
```

Considering this hierarchy, I need to be able to select the children of vegetable or fruit (carrot, leek, cabbage, strawberry...) or their categories (vegetable or fruit). I guess that would make less sense when the "multiple" option is active.
This allows the user to select a less specific option but still relevant in some cases.
Does that make more sense ?

**Comment by arendjr** [comment]
Oh, so the user should be able to select "vegetable" in addition to "carrot", "leek", etc.? That's actually possible! Just add the `selectable` property to the parent item with a value of `true`. But indeed, I don't see it being documented, so I'll keep this issue open for now.

**Comment by watsab** [comment]
Oh great! That's exactly why I need ! Thanks !
