### ISSUE TITLE
How do i override Style?

### ISSUE THREAD

**Issue by hungdev** [arendjr/selectivity#242]
hi @arendjr, this lib is nice.
but i dont know how to override style?
such as: override background color or width, height. I tried with style props:
`style: {{backgroundColor: 'red' }}` but its not run.
And please export clear docs api.
thank you.

**Comment by arendjr** [comment]
Thanks, @hungdev. You can override the style by adjusting the CSS that comes with Selectivity. There's no support for using React props to adjust styling (which I'm afraid would be too limited anyway).

For questions, please refer to StackOverflow rather than creating issues.
