### ISSUE TITLE
Positioning of Dropdown inside relative element

### ISSUE THREAD

**Issue by dmpol18** [arendjr/selectivity#27]
When selectivity element is inside of a position:relative element the opening of dropdown looks like a bug, `cos dropdown get its offset relatively to browser window (?) but not for the selectivity element, so the only way to fix it now is to set manually top and right css properties

It would be great to see an option to set dropdown relatively to input, not browser window.

**Comment by arendjr** [comment]
I think you can solve this by grabbing an updated copy. This was fixed last night: #22

**Comment by dmpol18** [comment]
Thank you!
