### ISSUE TITLE
Displaying long labels in multiple select

### ISSUE THREAD

**Issue by msx2** [arendjr/selectivity#31]
If multi-select item is too long in name, you can't remove it by clicking on `x` icon. Here's the effect of this:

![screen shot 2015-04-17 at 14 37 53](https://cloud.githubusercontent.com/assets/1129643/7202106/6173ca30-e50f-11e4-8683-2d75ac2c5b64.png)

@arendjr What do you think of moving the `x` icon to the left, just like in `select2`? This is the quickest and easiest fix I can think of. Otherwise we'd need to consider trimming the label in JS/rebuilding component introducing yet another `div`/`span` inside.

**Comment by arendjr** [comment]
Visually I really prefer them on the right, but you're making a good argument. Also I've noticed that removing multiple selections quickly is easier when the close button is left-aligned, so I'm fine with moving it to the left (just never gonna convince my employer to do the same :)).

**Comment by dlong500** [comment]
Can we revisit this?  I think many people are going to be expecting the close icon on the right.  Can we get an option for either side?  I think the most visually appealing option (whether the icon appears on the left or right) is to have an ellipsis truncate the text and contain the item within the component, but I'd settle for at least being able to choose the side for the icon for now.

**Comment by arendjr** [comment]
Well, one of the strengths of Selectivity is the ease with which you can customize the templates, so a custom template can give you exactly what you want:

    $input.selectivity({
        templates: {
            multipleSelectedItem: function(options) {
                var extraClass = (options.highlighted ? ' highlighted' : '');
                return (
                    '<span class="selectivity-multiple-selected-item' + extraClass + '" ' +
                          'data-item-id="' + _.escape(options.id) + '">' +
                        _.escape(options.text) +
                        '<a class="selectivity-multiple-selected-item-remove"><i class="fa fa-remove"></i></a>' +
                    '</span>'
                );
            }
        }
    })

This would put the close icon back on the right side (you might need to make a little CSS tweak to fix the padding). I admit it's a bit more work than a simple toggle option, but from here you can customize it in any way you prefer.
