### ISSUE TITLE
Dropdown positioning

### ISSUE THREAD

**Issue by msx2** [arendjr/selectivity#33]
As discussed in #24, the idea would be to use `position: relative` container, and append dropdown to this container, not to `body`. Thus, dropdown would have the following styling:

* `top: $actual-input-height` for bottom-oriented dropdown
* `bottom: $actual-input-height` for top-oriented dropdown

Also, there's an issue with detecting the orientation for the multiple select dropdown. If dropdown list does not fit the viewport height, no matter how much space it has at the top, it will open as top-oriented.

![screen shot 2015-04-17 at 15 32 38](https://cloud.githubusercontent.com/assets/1129643/7202915/0533c2c2-e517-11e4-80d0-15780fd51870.png)

I believe it should open as the bottom-oriented :)

The same situation makes single select dropdown also display in wrong place. It does open as bottom-oriented, but not attached to its trigger (`.selectivity-input`) - this will be fixed automatically while using `top`/`bottom` approach.

**Comment by arendjr** [comment]
This is now at the top of my list and also required to successfully close #7, hope I will get to this soon.

**Comment by msx2** [comment]
That's awesome, thanks :)
