### ISSUE TITLE
Method to 'disable' and 'enable' selection.

### ISSUE THREAD

**Issue by shoaibshakeel381** [arendjr/selectivity#37]
I need to disable/enable selection based on a second combo-box So currently i need methods to `disable` and `enable` selectivity so that user interaction with can be controlled.
Currently to achieve this i am doing this: If i need to disable selection then just destroy it. And if i need to enable it again then just apply selectivity again. I don't think this is a very good workaround. Most of other plugin also provide support for disabling user selection at runtime.

P.S: i know there's an option for declaring selectivity as readonly but i need to be able to change it at runtime through API call.

**Comment by arendjr** [comment]
Does it work for you to call `$selectivity.setOptions({ readOnly: true|false })`? In theory, that should toggle the readOnly behavior at runtime, but I admit I haven't tested it.

**Comment by shoaibshakeel381** [comment]
Yes it's working. Thanx.

**Comment by arendjr** [comment]
Cool. I've added the `setOptions()` method properly to the documentation now.
