### ISSUE TITLE
Allow `ajax` based options load in `select` elements.

### ISSUE THREAD

**Issue by shoaibshakeel381** [arendjr/selectivity#38]
Whenever we use `select` element `selectivity` uses its `option` to create `items` array. But we need to be able to override this behavior so we ourselves can define whether to load item dynamically in that situation or not. Currently we need to either use text `input` or some other `div` or `span` element. But In the end most suitable option will be to be able to use `select` element with ajax based options loading.

**Comment by arendjr** [comment]
So now when you specify the `query` option to initialize a traditional `<select>` element, it will overrule the embedded `<option>` elements and not use them to initialize the `items` array.

Hope that's what you meant :)

**Comment by shoaibshakeel381** [comment]
thanx. That's exactly what i wanted.

**Comment by shoaibshakeel381** [comment]
BTW, I was previously using `ajax` attribute to load and customize my data so that `selectivity` can fetch and display results. If i add `query` option too then it only picks up `ajax` settings and `query` function isn't called. Do i have to provide only one of them at a time or something? Can you please make the difference between `query` and `ajax` options a bit more clear. 

Documentation doesn't help when to use which one and how can we use both options so that options are loaded dynamically while using `select` elements.
