### ISSUE TITLE
Serious bug with keyboard navigation within dropdown

### ISSUE THREAD

**Issue by dlong500** [arendjr/selectivity#41]
There is a serious usability issue with keyboard navigation of the dropdown contents.

For example, let's look at the very first example (Select a single city).

1. I focus on the element and begin pressing the down arrow.  When getting to the last item visible and pressing the down arrow once more the whole page shifts so the bottom of the dropdown is at the bottom of the browser viewport.

2.  Now I start pressing the up arrow and move up to the first visible item in the dropdown.  Pressing the up arrow once more results in the page shifting so the top of the dropdown is at the very top of the browser viewport.

3. Now here is where it gets REALLY messed up.  If the mouse position happens to be over the dropdown area, then whenever the keyboard navigation in the dropdown moves past the first or last visible item in the dropdown not only will the above two issues occur but the item under the mouse cursor gets selected which can result in a loop making it extremely hard to actually move up or down the list of items.

Issues 1 and 2 happen in Chrome, Firefox, and IE10.  Issue 3 happens in Chrome and Firefox, but interestingly enough doesn't seem to happen in IE10.

It's hard to explain in writing.  The best thing is just to test out the keyboard navigation on the example page.

**Comment by arendjr** [comment]
Good point, I know exactly what you mean. Have experienced it myself, but haven't found a good way around it yet. Thanks for making the report, and I hope together with #7, I can solve this for the next release.

**Comment by arendjr** [comment]
Point 3 is now fixed with commit bfe13d6. Don't know what to do about the first two, that seems inherent to using `scrollIntoView()`. But given that I think you agree point 3 was the worst culprit, I'm closing this one. If not, you can reopen :)

**Comment by dlong500** [comment]
Point 3 was the worst, but honestly I can't use this in my projects with the other two issues either.  It's just too problematic especially on large forms with pages that are larger than the viewport as it causes things to jump all around, and when moving up in the list you can't even see the element itself, only the dropdown list.

I'm not an expert at what is involved, but none of the other select/type-ahead components I've tested have the issue where the actual page itself moves when browsing the list using a keyboard so it does seem to be possible to fix, though it could be a larger refactor if your code is using a different methodology than other similar components.
