### ISSUE TITLE
Item partially out of view when scrolling list with keyboard

### ISSUE THREAD

**Issue by dlong500** [arendjr/selectivity#43]
I'm thrilled that you fixed the #41 issue!

However I noticed a relatively minor issue when scrolling down through the list with the keyboard where the item at the bottom of the list is halfway out of view.  This is probably a very easy fix but I'm not sure where to look.  Screenshot attached.
![selectivity_keyboard_nav1](https://cloud.githubusercontent.com/assets/430481/7638031/11415438-fa40-11e4-85fa-b8edc6c1c87a.png)

**Comment by arendjr** [comment]
Fixed! Issue seemed to only occur with jQuery.
