### ISSUE TITLE
Unable to Select Matched Results with Mouse

### ISSUE THREAD

**Issue by shiv86** [arendjr/selectivity#44]
Hi I am unable to select the matched results with a mouse. I can hit the "down" key on the keyboard to highlight a result and hit the "enter" to select a result. But I cant hover over a result and click with mouse to select it:

```javascript
var self = this;
var staticdata = [{ id: 1, text: 'bug' }, { id: 2, text: 'duplicate' }, { id: 3, text: 'invalid' }, { id: 4, text: 'wontfix' }];
	self._selectivity = self.$().selectivity({
        items: staticdata,
        placeholder: 'No city selected',
        multiple: true
});
```

**Comment by arendjr** [comment]
Sorry, I cannot reproduce this problem. What exactly is this `$()` that you're referencing? What kind of element does it refer to?

**Comment by arendjr** [comment]
Wait, are you using IE11 by any chance? I was just testing it there, and I can now reproduce it.
