### ISSUE TITLE
returning data

### ISSUE THREAD

**Issue by tpbsv77** [arendjr/selectivity#45]
If I just want to query the DB based off the search term entered, what do I need to return? I am getting an offset and map error when I just return an object. I can not find an example of simple data return.

**Comment by arendjr** [comment]
By "return", do you mean what you should pass to the callback function? You should pass it an object with `results` and `more` properties. The `results` are an array with objects containing `id` and `text` properties. For examples:

    $('#my-element').selectivity({
        query: function(query) {
           query.callback({
              results: [{ id: 1, text: 'First' }, { id: 2, text: 'Second }],
              more: false
           });
        }
    })
