### ISSUE TITLE
Error when using submenu with "showSearchInput": true and "multiple": true

### ISSUE THREAD

**Issue by XavM** [arendjr/selectivity#46]
The following error occurs when using submenu with "showSearchInput": true and "multiple": true : 

> Uncaught TypeError: Cannot read property 'before' of null                   in selectivity-full.js:3611

with selectivity-full.js:3611 being the **this.$searchInput.before** from **_renderSelectedItem**

Basic example : 

      $('#example-1').selectivity(
      {
        "items": [
        {
          "id": 1,
          "text": "one",
          "submenu":
          {
            "items": [
            {
              "id": 1,
              "text": "subOne"
            },
            {
              "id": 2,
              "text": "subTwo"
            }],
            "showSearchInput": true
          }
        }],
        "placeholder": 'No filter selected',
        "multiple": true
      });

A basic example reproducing the error is available here : https://jsfiddle.net/XavM75/fwnjx1b9/3/

**Comment by arendjr** [comment]
Thanks for the fiddle, really helped in reproducing and writing the test case!
