### ISSUE TITLE
jquery 'too much recursion' error when showSearchInputInDropdown is false

### ISSUE THREAD

**Issue by DoctorMalboro** [arendjr/selectivity#48]
I have the following piece of code:
```javascript
function set_subtipo_espectaculo_selectivity() {
    $('#subtipo').selectivity({
        allowClear: false,
        placeholder: 'Seleccione un subtipo de espectáculo',
        showSearchInputInDropdown: false
    });
```

Which produces this error:
```
too much recursion
/script/jquery.min.js
Line 4614
```

But if I comment **showSearchInputInDropdown** it works perfectly. Now, the code with or without the error does its job, but I find it odd to produce such error.

**Comment by dominicmartin** [comment]
Same problem with this code:

    $("#selector").selectivity({
        allowClear: false,
        showSearchInputInDropdown: false,
    });

Any solutions yet?

**Comment by Oxicode** [comment]
Tío. Si inicializas el$ ('#subtipo').selectivity en disable. Y en tu función set_subtipo_espectaculo_selectivity lo habilitas??

**Comment by DoctorMalboro** [comment]
@dominicmartin Nothing yet.
@Oxicode Simplemente lo inicializo en `$(document).ready(function () { set_subtipo_espectaculo_selectivity() });`

**Comment by arendjr** [comment]
Hey guys, sorry for the late reply! I have investigated the issue and started working on a fix. The proper fix is a bit complicated though, so please bear with me :) Hope to keep you posted!

**Comment by arendjr** [comment]
Okay, I've pushed updated builds to the repository just now. Can you test whether they solve your problems? If it's fixed I would like to release a new version. Thanks!

**Comment by DoctorMalboro** [comment]
I just tested it and the fix works. Thanks!

**Comment by arendjr** [comment]
Good to hear! Hope to publish the new release soon!
