### ISSUE TITLE
Another way to implement multiple selection

### ISSUE THREAD

**Issue by dzek69** [arendjr/selectivity#57]
Hi,
I don't like Select2. Just like you - I began to write my own implementation of `<select>` replacement script. I gave up because I felt like I'm starting to getting lost with it - I've never had written proper JS library - so my script currently likes to position dropdown wrong (should be easy to fix) and has no support for `<optgroup>` (harder to fix). I've tried many such scripts, but none of them managed to get one thing "right" for me - the multiple selections. Look what I've done:
https://www.dropbox.com/s/o2eqyf9no7kiy4m/2015-08-04_09-19-17.mp4?dl=0 (175KB, no worries about big DL)

I'd like to request something like that.
I select one element - it looks just like a single dropdown. I select two or more (I can just click-click-click and dropdown stays open) - it just shows "Multiple selection [count]". My script had (AFAIR I removed it for some reason) also an option to show selected items separated by comma. It's not a big deal to change this anyway and I'll be happy with any of this.

Do you think you'll be able to implement such thing? What do you think about this idea?

Oh, and if you for some reason want to see my library I can publish it. I was planning to do this when I think I'm happy with the results, but currently I am not.

**Comment by dzek69** [comment]
no thoughts?

**Comment by arendjr** [comment]
Seems you posted this just a few days before my wedding when I had other things on my mind :) Then I forgot about it, sorry!

But currently I don't really have a use case for this myself, so I don't think I'll implement this myself in Selectivity.

If you're interested in implementing this in your own InputType module for Selectivity I think I would be interested though, so if you want to do that, please re-open this ticket.

Cheers!
