### ISSUE TITLE
way to distinct between closed, hover and open state

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#59]
It would be nice to have some way to change styling depending on what state the dropdown is in.

This would mean that we would need to add class to the selectivity-*-select when desired state is activated.

onHover: class="hover"
whenOpen: class="open"

**Comment by niom** [comment]
I can create a pull request for this feature if you consider it to be useful and would add value to the project.

**Comment by arendjr** [comment]
Great, sounds like something more people might appreciate, so please do :)
Please also include a little test case to verify the behavior is correct. Thanks!

**Comment by niom** [comment]
Created a PR #80 that resolves this feature.

Is there any other way to do proper development than creating functionality that is covered with tests?
