### ISSUE TITLE
User avatar image for a userlist selector

### ISSUE THREAD

**Issue by jasondavis** [arendjr/selectivity#60]
With Select2 I am able to build a userlist selector which shows a username next to a thumbnail avatar image.  Once a user is selected, it also shows the image and name.

Is this possible using the templates in this library>  I didn't see any images in the demos so I am assuming it might not be?

BTW great library!

**Comment by arendjr** [comment]
Thanks! Sorry for the late reply (just left on my 7-week honeymoon when you asked the question :p), but yes, this is surely possible. You can pass a `templates` option when constructing a Selectivity instance, or just overwrite the templates defined in `Selectivity.Templates` if you want to globally override them. Templates can contain any HTML you like, including images. While not officially documented, you can add additional properties to your items besides the obligatery `id` and `text` properties, and you should be able to access those from the templates.

Documentation for the templates themselves can be found here: https://github.com/arendjr/selectivity/blob/master/src/selectivity-templates.js

Cheers!
