### ISSUE TITLE
Give search term to url function

### ISSUE THREAD

**Issue by bwbecker** [arendjr/selectivity#67]
The URL for an ajax request can currently be specified with a string or a function.  However, the function doesn't appear to take parameters, so I'm not sure what it can do except return a constant.  I'd like to have it passed the search term so I could return a URL such as

return http:/something/search_term;

or even 

if (search_term === 'today')
   return http://clients_i_searched_for_today
else
   return http://something/search_term

Thanks for your excellent work!

**Comment by shoaibshakeel381** [comment]
+1

**Comment by arendjr** [comment]
The `url` function will now receive an options object with `offset` and `term` properties, just like the Selectivity `query` option method.

Cheers!

**Comment by shoaibshakeel381** [comment]
thanks a lot. :ok_hand: .
