### ISSUE TITLE
Configuring the local messages

### ISSUE THREAD

**Issue by juanjosesanchezesteban** [arendjr/selectivity#69]
I need to set up local messages based on the user's language. How I can change the Selectivity.Locale before calling .selectivity?

Thank you!

**Comment by msx2** [comment]
Here's a jQuery's example of setting additional language - https://github.com/msx2/selectivity-rails/blob/master/app/assets/javascripts/selectivity.pl_PL.js.coffee

**Comment by juanjosesanchezesteban** [comment]
Great. Thank you!
