### ISSUE TITLE
Adding and Submitting data from multi select box

### ISSUE THREAD

**Issue by zelin** [arendjr/selectivity#70]
I am using this simple code to show multiselect searchbox

$('#storename').selectivity({
        items: stores,
        multiple: true,
        placeholder: 'Type to search a store',
        query: queryFunction,
        
    });    

I have couple of additions to make.

Firstly, i want to get a list of all items selected separated by commas. when i click submit for a form. How can i do that? I have an INPUT Tag hidden, i can put items selected but how can i put selected items in it?

Secondly, if i have a comma separated tags, how can i place it in search box

**Comment by arendjr** [comment]
Hi there! To get a comma-separated list of selected item IDs you can try this: `$('#storename').selectivity('value').join(',')`. You can use regular jQuery commands for storing that in a hidden input tag or a search box. Cheers!
