### ISSUE TITLE
preventDefault form submit on keydown with KEY_ENTER

### ISSUE THREAD

**Issue by schorsch** [arendjr/selectivity#75]
when using keyboards enter key- KEY_ENTER to select an element, the surrounding form gets submitted.

I think the problem is in the event definition https://github.com/arendjr/selectivity/blob/master/src/selectivity-keyboard.js#L170:

    $input.on('keydown', keyHeld).on('keyup', keyReleased);

where the first keydown function does not prevent the default (form submit) for the KEY_ENTER.  

I dont have any other listeners and dont know why the browser(chrome) submits the form on the keydown event. Anyway adding the following to the keyHeld function https://github.com/arendjr/selectivity/blob/master/src/selectivity-keyboard.js#L116 ff seems to resolve the issue:

            } else if (event.keyCode === KEY_TAB) {
                setTimeout(function() {
                    selectivity.close({ keepFocus: false });
                }, 1);
            } else if (event.keyCode === KEY_ENTER ) { // no submit on keydown
                event.preventDefault();
            }

**Comment by arendjr** [comment]
Thanks, I've added your suggestion for handling the Enter key!
