### ISSUE TITLE
Clear selectivity input

### ISSUE THREAD

**Issue by LorenzoPirondini** [arendjr/selectivity#76]
Hi, 
i am working on a project with a few selectivity inputs, how can i remove all items selected from a selectivity instance without using ID or Object ? i just need to kill a selectivity instance and replace it with a new one, but the items slected stay on the field.

Edit: i found in selectivity-base.js that i can use 
$('#selector').selectivity('destroy'); 
to kill the selectivity instance, that solves one of my problem.

Any ideas on how i could just remove all selected items whitout destroying the selevtivity instance?

**Comment by arendjr** [comment]
Hi there, you can do this using the clear() method:

    $('#selector').selectivity('clear');

I see that has not been documented yet on the homepage, so I'll it there. Thanks!

**Comment by LorenzoPirondini** [comment]
Hi, thanks very much for the hint. 
It looks like the "destroy" method is not documented neither.

**Comment by arendjr** [comment]
Yeah, you're right. Guess I should add that too :)

For what it's worth, I actually try to differentiate between the public API and the documented API. The idea is that even though I follow semver and will bump the major version if I change the public API, I try extra hard to avoid changes to the documented API to minimize annoyance among users. The assumption is that people who find the other public methods (they're still documented in the sources as you discovered) are probably more experienced and more willing to get their hands dirty with the internals, possibly creating their own modules. It also prevents a lot of questions from the less experienced users about how to use some of the more advanced methods that are still part of the public API. Don't know how viable it is yet as a long term strategy, but that's the idea anyway :)

All that said, `destroy()` is very unlikely to change and not very likely to confuse any users, so I'll add it to the documented API as well.
