### ISSUE TITLE
Highlight currently selected option

### ISSUE THREAD

**Issue by alesdotio** [arendjr/selectivity#78]
If a value is selected and you open the dropdown, the currently selected option should be highlighted instead of the first one.

Steps to reproduce:
* go to the first example on https://arendjr.github.io/selectivity/
* click the select and choose "Barcelona"
* click the select again, "Amsterdam" is now highlighted

Expected:
* "Barcelona" should be highlighted

**Comment by claudeschneider** [comment]
+1 for this feature, and extra reasoning for it:
If there are a lot of options in the select, their current selection may be out of view, and require a lot of scrolling to get to (e.g. choosing a timezone, or time of day).
Biggest pain point is using it for a time-picker. I pre-set a 12 noon value, so they can scroll up/down equally to find their required time. At the moment, it opens at 12am at the top, and they have to scroll lots to get to evening times.

**Comment by niom** [comment]
+1 for this. Feels kind of odd when the selected value is not selected.
