### ISSUE TITLE
Separate awesome-font dependency to separate module

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#83]
It would be better for projects that don't want to use awesome-fonts that it wouldn't be a direct dependency to the project.

or is this just some legacy in bower.json?

**Comment by arendjr** [comment]
The reason it's there is because the default setup requires them, but to be honest I'm not that familiar with Bower to know if there's a better way to do it?

**Comment by niom** [comment]
With a quick search I could not find any references to the awesome fonts except from the demo files and in there it was using direct cdn link. 

Am I missing something?

**Comment by niom** [comment]
Maybe this is not relevant. Closing.
