### ISSUE TITLE
Enable Travis-CI to the project

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#86]
Would be really great if everything would be tested automatically by Travis. 

We could add at least
- running tests
- jshint

Enabling this would make reviews much more easier.

**Comment by arendjr** [comment]
You're right. Travis-CI is now enabled in the development branch.

Btw, there's also a script called `install-git-hooks.sh` in the `tools/` subdirectory. That's the one I always use to make sure I don't check-in rubbish :)

**Comment by niom** [comment]
I was about to play with this too but you where faster. :)

I'll need to put that hook in to use.
