### ISSUE TITLE
building with latests npm fails

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#89]
apparently we have some old dependencies that don't work with the latest npm.

maybe we should update the dependencies in package.json?

**Comment by arendjr** [comment]
Oh, I just updated some of them yesterday, but I guess the others can be done as well. Which one was failing for you?

I'm using Node 4.2.3 LTS myself, and everything still seems fine there.

**Comment by niom** [comment]
Hah my bad, I had old packages in my node_modules after your upgrade.

everything working.
node: 5.1.0
npm: 3.3.12
