### ISSUE TITLE
Release notes are missing

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#92]
There are no release notes. This would work as a good communication for the users of the library.

The project that I'm working with is using something like this:
````
#HEAD
[#ref to PR]: new cool stuff
[#ref to PR]: heavy refactoring. Will break backward compatibility of...

#1.2.1
[#ref to PR]: fixed a bug

#1.2.0
[#ref to PR]: some new feature
````

This means that everyone should use branches and PRs for development and master would become the stable place where releases could be done when needed. Merging to master would be allowed only when branch is green.

**Comment by kevin-brown** [comment]
Release notes appear to be available on the releases page.

https://github.com/arendjr/selectivity/releases

**Comment by arendjr** [comment]
@kevin-brown is right, that's where I've kept them uptil now and will keep posting them. But I also agree it would be better to have a CHANGELOG in the repository that I can use as a source when publishing release notes. Will do!
