### ISSUE TITLE
Moving to the next field with the tab key

### ISSUE THREAD

**Issue by ritcoder** [arendjr/selectivity#94]
Is there a way to move to the next field in a form? The issue is that I'm unable to move to the next or previous value after the value has been selected from the drop down list. My inputType is Single.

One observation is that it works when the text field with the drop down has focus, tabbing works.

Is there a way around this?

**Comment by arendjr** [comment]
Hm, I can confirm this, but I don't have a good fix for this right now. Hope I get around to fixing this soon, but otherwise any PR to fix this would be appreciated!

**Comment by niom** [comment]
Apparently PR #91 would fix this (focusing page top after selecting an item and pressing tab). Maybe this has something to do with the backdrop mixing up where the next tab should go.

**Comment by arendjr** [comment]
PR has been merged. @ritcoder can you confirm this PR solved the issue for you? Thanks!

**Comment by arendjr** [comment]
I'm gonna go ahead and assume this has been resolved satisfactorily :)
