### ISSUE TITLE
Accessibiliity 

### ISSUE THREAD

**Issue by mgifford** [arendjr/selectivity#98]
Could you clean up the known accessibility errors from 

http://wave.webaim.org/report#/https://arendjr.github.io/selectivity/
http://tenon.io/testNow.php?url=https://arendjr.github.io/selectivity/

Was good to see the prior issue about Keyboard Accessibility, but I think there are still some issues with that.

**Comment by arendjr** [comment]
PR would be accepted, but personally I don't really care about accessibility issues on the website, given that the majority of the reported errors are from the GitHub template I used and not from content. (Though yes, I do agree the nested tables are ugly, so I might do something about that :)

**Comment by mgifford** [comment]
Thanks for the comment. Unfortunately, sometimes it is hard to see the forest for the trees when there are a lot of accessibility errors in the surrounding template. 

I don't think I'll have time to do this, but hopefully someone else submits a PR.
